### ISSUE TITLE
How to use it FlashBios?

### ISSUE THREAD

**Issue by hoacongankg** [xiaoMGitHub/LEGION_Y7000Series_Flash_BIOS_Tools#2]

**Comment by xiaoMGitHub** [comment]
Open the bat script and execute the corresponding options.

**Comment by hoacongankg** [comment]
XiaoM, you can update OC 0.6.6 to 0.6.9 .?

**Comment by xiaoMGitHub** [comment]
The current EFI can still meet the use of the latest system (11.4). It will naturally be updated when it does not support booting the latest system.
